
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV['PG_DB_USER'] %>
  password: <%= ENV['PG_DB_PASS'] %>

development:
  <<: *default
  database: development_cars_for_teens

test:
  <<: *default
  database: test_cars_for_teens
