
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: development_cars_for_teens

test:
  <<: *default
  database: test_cars_for_teens
